brian-team/brian2cuda

brian2cuda/device.py

Until now we just checked for occurences of `_postsynaptic_idx`,
`_presynaptic_idx` and `_idx` in `variable_indices` passed to `CUDAStandaloneDevice.code_object()`. But just reading variables doesn't lead to
race conditions, so we need to check for variables that will be written to in `vector_code`.
Tests running now.

Set synaptic propagation modes only if variables are modified

---

brian2cuda/cuda_generator.py
brian2cuda/device.py
brian2cuda/templates/objects.cu
brian2cuda/templates/ratemonitor.cu
brian2cuda/templates/run.cu
brian2cuda/templates/spikegenerator.cu
brian2cuda/templates/spikemonitor.cu
brian2cuda/templates/threshold.cu

We now just pass `t` and `dt` clock variables by value in
KERNEL_PARAMETERS if a kernel need them. This reduces the previous
`cudaMemcpy` overhead for small networks significantly.

Remove clock synchronization (host->device) at each clock cycle

---

brian2cuda/templates/objects.cu
brian2cuda/templates/rand.cu

Before we created them every clock cycle which creates significant
overhead. This implementation still needs to call one
`cudaMemcpyToSymbol` per clock cycle and codeobject using rand/randn,
which could be avoided.
This implementation very generically generates a max of `50MB` of random number per codeobject and regenerates them after they are used up. This way for mall simulations we only generate once and for bigger simulations (where memory is a potential limit), we don't generate too many numbers. 
This is a quick and dirty solution here which might fail if we run into memory limits. but for our current benchmarks its good enough and since we should probably use a cleaner buffer system at some point, I will leave it like this for now.

Create random numbers in bigger chunks

---

.gitmodules
brian2cuda/brianlib/spikequeue.h
brian2cuda/cuda_generator.py
brian2cuda/device.py
brian2cuda/templates/objects.cu
brian2cuda/templates/ratemonitor.cu
brian2cuda/templates/synapses_classes.cu
brian2cuda/tests/features/cuda_configuration.py
brian2cuda/tests/test_cuda_generator.py
brian2cuda/tools/run_single_test.py
brian2cuda/tools/run_test_suite.py
brian2cuda/tools/run_test_suite_on_current_state.sh

PR for #37.
Our brian2 submodule now tracks the `float32_support` branch at my brian2 fork (denisalevi/brian2). This way we have the single precision support that we need and can easily pull any changes in the brian-team/brian2@float32_support branch. But if that branch stays unmerged, we can also merge in the updated master branch when needed. I don't see an easier solution right now if we want the single preference support.
The tests are passing except for the known issues and an additional issue when connecting synapses to synapses (not a new bug, just overseen before, see #133 ).
We can now also run all tests with single precision preference.

Add single precision support

---

brian2cuda/device.py
brian2cuda/tests/test_stringtools.py
brian2cuda/utils/__init__.py
brian2cuda/utils/stringtools.py
examples/cuba_cuda.py

This is a PR for #148 
1. use single precision for `dt` variable in code objects
2. use single precision for constant literals
3. cast time differences in even-driven stateupdates to float `float(t-lastupdate)`

Make single precision mode more efficient

---

brian2cuda/device.py
brian2cuda/templates/spikemonitor.cu
brian2cuda/templates/statemonitor.cu

This minor change is necessary for compatibility with latest Brian 2 master (after the merge of brian-team/brian2#1022). Changes were necessary to fix brian-team/brian2#1017, the details are explained there but I don't think it is necessary to understand them fully.
All that is important is that the changes proposed with this PR should not change anything for earlier versions of Brian 2 and will prevent weird failures when you update to latest Brian 2 master :)

Port recent changes from Brian 2 

---

brian2cuda/device.py
brian2cuda/tools/remote_run_scripts/on_headnode.sh
brian2cuda/tools/remote_run_scripts/run_test_suite_on_cluster.sh
brian2cuda/tools/run_test_suite.py

Remove unnecessary pointer copies in `%KERNEL_VARIABLES% inside codeobject kernels. Define pointer and variable keywords in the function definition (`%DEVICE_PARAMETERS%`) instead.
Good to go once tests have passed (running).

Cleanup KERNEL_VARIABLES

---

brian2cuda/__init__.py
brian2cuda/codeobject.py
brian2cuda/cuda_generator.py
brian2cuda/device.py
brian2cuda/templates/common_group.cu
brian2cuda/templates/group_variable_set.cu
brian2cuda/templates/group_variable_set_conditional.cu
brian2cuda/templates/ratemonitor.cu
brian2cuda/templates/spatialstateupdate.cu
brian2cuda/templates/spikegenerator.cu
brian2cuda/templates/spikemonitor.cu
brian2cuda/templates/statemonitor.cu
brian2cuda/templates/summed_variable.cu
brian2cuda/templates/synapses.cu
brian2cuda/templates/synapses_initialise_queue.cu
brian2cuda/templates/synapses_push_spikes.cu
brian2cuda/templates/threshold.cu
brian2cuda/tests/test_functions.py
brian2cuda/tests/test_not_implemented_brian2_test_suite_fails.py
brian2cuda/timedarray.py
brian2cuda/tools/remote_run_scripts/run_test_suite_on_cluster.sh
dev/benchmarks/helpers.py
frozen_repos/brian2.diff

Add cuda implementation for TimedArray

---

brian2cuda/device.py
brian2cuda/templates/network.cu
brian2cuda/templates/objects.cu
brian2cuda/templates/spikegenerator.cu
brian2cuda/templates/threshold.cu

Fixes bug in periodicity (see #48) and and implement correct spikespace usage when having homogeneous delays.
Tests are running.
The spikegenerator template could be further optimized, but I am leaving this for another time (see #193).
Additional TODOs:

Fix spikegenerator.cu template

---

brian2cuda/tools/remote_run_scripts/_load_remote_config.sh
brian2cuda/tools/remote_run_scripts/remote_execute_main.sh
brian2cuda/tools/remote_run_scripts/remote_make.sh
brian2cuda/tools/remote_run_scripts/remote_sync.sh
brian2cuda/tools/remote_run_scripts/remote_sync_make_execute.sh

Not sure if I need to create a pull request to this or a forked repository.

Changing shebang

---

brian2cuda/tools/remote_run_scripts/_load_remote_config.sh
brian2cuda/tools/remote_run_scripts/run_test_suite_on_cluster.sh

3 changes - 
2 in `run_test_suite_on_cluster.sh` 
1 in `_load_remote_config.sh`

3 changes regarding git running tests

---

brian2cuda/cuda_generator.py
brian2cuda/cuda_prefs.py
brian2cuda/device.py
brian2cuda/tests/test_cuda_generator.py
brian2cuda/tests/test_gpu_detection.py
brian2cuda/tests/test_synaptic_propagations.py
brian2cuda/tools/utils.py
brian2cuda/utils/gputools.py
dev/benchmarks/results_2018_08_27_complete_before_september/merope_heterogeneous_no_bundle_no_atomics/run_speed_test_script.py
dev/benchmarks/run_manunscript_runtime_vs_N_benchmarks.py
dev/benchmarks/run_speed_tests.py
dev/documentation/preferences.txt
examples/utils.py

I have two queries 
1. Should I change the strings present in logger.py 
2. In `run_speed_test_script.py`, we see `prefs['devices.cuda_standalone.profile'] = 'blocking'` , but such a preference is not present. Should I add it ?
I have also pushed changes for [#140](https://github.com/brian-team/brian2cuda/issues/140) here.
The output is 
```
INFO       CUDA installation directory detected via location of `nvcc` binary: /usr/local/cuda [brian2.devices.cuda_standalone]
INFO       Automatic detection of GPU names and compute capabilities disabled, using manual preferences [brian2.devices.cuda_standalone]
INFO       Compiling device code for GPU 0 [brian2.devices.cuda_standalone]
INFO       Compiling device code for compute capability 7.5 (compiler flags: ['-arch=sm_75']) …
```

Issue 195: Refactoring prefs

---

brian2cuda/cuda_prefs.py
brian2cuda/utils/gputools.py

Before, `CUDA_DEVICE_QUERY` had not effect for GPU selection in brian2cuda. This PR should fix that. 
This needs some tinkering around with the different IDs (the ones reported by `nvidia-smi`, which ignores `CUDA_VISIBLE_DEVICES`) and the ones defined by `CUDA_VISIBLE_DEVICES` (which e.g. `deviceQuery` takes into account).
Here is the updated doc for the `gpu_id` preferences. This is how it should work. What is missing is that with `prefs....gpu_id = None` and `CUDA_VISIBLE_DEVICES` set, it still ignored `CUDA_VISIBLE_DEVICES` currently.
The ID of the GPU that should be used for code execution. Default value is
`None`, in which case the GPU with the highest compute capability and lowest ID
is used.
If this preference is set, it has to be the ID reported by `nvidia-smi`, which
ignores the …

Acknowledge `CUDA_DEVICE_QUERY` during GPU selection

---

brian2cuda/device.py
brian2cuda/tests/test_cpp_cuda_consistency.py
brian2cuda/tests/test_cuda_generator.py
brian2cuda/tests/test_cuda_standalone.py
brian2cuda/tests/test_functions.py
brian2cuda/tests/test_gpu_detection.py
brian2cuda/tests/test_network_multiple_runs.py
brian2cuda/tests/test_not_implemented_brian2_test_suite_fails.py
brian2cuda/tests/test_profiling.py
brian2cuda/tests/test_random_number_generation.py
brian2cuda/tests/test_synaptic_propagations.py

PR implements changes following brian-team/brian2#1104
Closes #173 
To my surprise, the `CPPStandaloneDevice.delete()` function works without modification for our `CUDAStandaloneDevice` (which inherits it). I thought we had a few additional header files at least in `brianlib`, but those are deleted as well. Didn't look into it in detail, if it works, it works!

Add support for deleting standalone code / results

---

brian2cuda/templates/ratemonitor.cu
brian2cuda/templates/statemonitor.cu
brian2cuda/tests/test_monitor.py
brian2cuda/tests/test_spikegenerator.py
brian2cuda/tests/test_synaptic_propagations.py

This PR fixes #50 and our equivalent of brian-team/brian2#1119.
I opened #201 as follow-up issue of #50 with unsolved comments (statemonitor only uses 1 block currently).
Tests are running.

Fix monitor indexing issues

---

brian2cuda/device.py
brian2cuda/templates/common_group.cu
brian2cuda/templates/group_variable_set_conditional.cu
brian2cuda/templates/main.cu
brian2cuda/templates/makefile
brian2cuda/templates/run.cu
brian2cuda/tests/func_def_cuda.cu
brian2cuda/tests/func_def_cuda.h
brian2cuda/tests/test_functions.py

This PR implements support for:
- `codegen.cpp` preferences which set include/lib directories. These preferences are passed down to the C++ compiler. Generally, we just use the same flags generated for C++ Standalone compilation (by `distutils.ccompiler`) but modify them such that `nvcc` understands them and passes them correctly to the C++ compiler (via `-Xcompiler`) or to the linker `(via `-Xlinker`). This is not thoroughly tested (I don't know what options `distutils` might generate on other systems than mine). But I think it is good enough for now, if there are problems for some use cases, we can fix that later.
- external source files for `cuda_standalone` functions (see [here](https://brian2.readthedocs.io/en/stable/advanced/functions.html?highlight=header#external-source-files))
- …

Support external header files and compiler keywords

---

brian2cuda/tests/conftest.py
brian2cuda/tests/test_stateupdaters.py
brian2cuda/tools/test_suite/run_single_test.py
brian2cuda/tools/test_suite/run_test_suite.py

See #183, I didn't check yet for all tests that could be converted, just did the `test_stateupdater.py`.
This PR also introduces a `brian2cuda/tests/conftest.py` file that updates the `fake_randn_randn_fixture` with a CUDA Standalone function implementation, which is needed for the added tests.
For the new `conftest.py` to be loaded, I had to set a new `--confcutdir` since our tests reside outside the `brian2` folder (and brian2 test suite sets `--confcutdir=/path/to/brian2`.

[MRG] Add `standalone_compatible` versions of otherwise Runtime only stateupdater tests

---

brian2cuda/cuda_prefs.py
brian2cuda/device.py
brian2cuda/tests/conftest.py
brian2cuda/tests/test_gpu_detection.py
brian2cuda/tests/test_monitor.py
brian2cuda/tools/test_suite/run_single_test.py
brian2cuda/tools/test_suite/run_test_suite.py
brian2cuda/tools/test_suite/run_test_suite.sh
brian2cuda/tools/test_suite/utils.py
brian2cuda/utils/gputools.py
frozen_repos/brian2.diff

Since commit brian-team/brian2@9c239bc1, the brian2cuda tests fail because the `setup_and_teardown` fixtures are not loaded anymore. I didn't why that is the case. Before that commit, the fixtures defined in `brian2/conftest.py` were loaded for all tests (even outside the `brian2` directory), because I set `--rootdir=brian2` (and the `conftest.py` in the `rootdir` should be loaded for all tests).
I don't know why things stopped working now. Maybe the [@pytest.hookimpl](https://github.com/brian-team/brian2/blob/a71abd338a50a916863230b5d648012d3542666b/brian2/conftest.py#L94) is not loaded for all tests? And also wasn't before the commit, which I never tested since I run the test suite with `fail_for_not_implemented=True`? And since the `reinit_and_delete` moved in the hook function, this …

[MRG] Fix pytest fixture loading for brian2cuda tests

---

brian2cuda/cuda_generator.py
brian2cuda/tests/test_random_number_generation.py
frozen_repos/brian2.diff

See #200 
This adds CUDA implementations for default functions `expm1`, `log1p` and `exprel`, while `exprel` is not type-safe in single-precision mode yet, see #233.
The brian2 update also included a change of integer types to `site_t` types, which I haven't implemented yet, see #230 .

[MRG] Support last brian2 version with Python 2 support

---

brian2cuda/templates/common_group.cu
brian2cuda/templates/common_synapses.cu
brian2cuda/templates/group_variable_set.cu
brian2cuda/templates/group_variable_set_conditional.cu
brian2cuda/templates/ratemonitor.cu
brian2cuda/templates/reset.cu
brian2cuda/templates/spatialstateupdate.cu
brian2cuda/templates/spikegenerator.cu
brian2cuda/templates/spikemonitor.cu
brian2cuda/templates/statemonitor.cu
brian2cuda/templates/stateupdate.cu
brian2cuda/templates/summed_variable.cu
brian2cuda/templates/synapses.cu
brian2cuda/templates/synapses_create_array.cu
brian2cuda/templates/synapses_create_generator.cu
brian2cuda/templates/synapses_initialise_queue.cu
brian2cuda/templates/threshold.cu

See https://github.com/brian-team/brian2/pull/1155
I tried to keep the template format similar to cpp_standalone. Just a few minor changes.
One could probably also let our `synaspes_push` tempalte extend `common_group`, but that needs a bit of restructuring. What we would get though is removing the duplicate occupancy calculation code. Didn't do that yet.

Template overhaul

---

brian2cuda/device.py
brian2cuda/tests/test_random_number_generation.py

The curand host API can only generate an even number of random numbers. For codeobjects that run only once, we didn't round up the number to even, now we do.

Fix uneven curand rng

---

brian2cuda/cuda_generator.py
brian2cuda/device.py
brian2cuda/templates/common_group.cu
brian2cuda/tests/test_functions.py
brian2cuda/tests/test_random_number_generation.py
brian2cuda/tests/test_stateupdaters.py
brian2cuda/tests/test_stringtools.py
brian2cuda/utils/stringtools.py

PR for #234 
Remaining lower priority single precision issues are collected in #264

Fix single precision mode

---

brian2cuda/templates/synapses.cu

We were serializing over spiking neurons (left over from old times when we didn't have atomics yet). Now in synapses mode, where we don't need and don't use atomics, we also parallelize over spiking neurons.

Fix parallelization for synaptic effects in `synapse` mode

---

brian2cuda/templates/common_group.cu
brian2cuda/templates/objects.cu
brian2cuda/templates/statemonitor.cu
brian2cuda/tests/features/speed.py
brian2cuda/tests/test_monitor.py

Fixes StateMonitor to work with >1024 recorded neurons. And removes some unnecessary copying of `N` and `t` variables between host and device memory.
This closes #201 
Some further straight forward optimizations of the `StateMonitor` are collected in #278

Fix statemonitor

---

brian2cuda/device.py
brian2cuda/templates/objects.cu
brian2cuda/templates/spikemonitor.cu
brian2cuda/tests/test_monitor.py

Fixes #286 
This implementation is a quick solution that does the following when recording with `SpikeMonitor` from a `Subgroup`.
- In Brian2CUDA, each `NeuronGroup` has its own spikespace, which is filled with the neuron IDs of spiking neurons. In `cpp_standalone`, this spiekspace is sorted by neuron IDs. In Brian2CUDA, it is not, which is why we can't just read a consecutive subsection of the spikespace, where all neuron IDs belong to one `Subgroup`.
- Instead, this implementation calls `thruds::count_if` to get the number of spiking neurons in the `Subgroup` and then calls `thrust::copy_if` to copy those IDs into another array (spikespace for subgroup).
- This means we can use the same spikemonitor kernel for `NeuronGroup` and `Subgroup` recordings, but passing a different spikepace …

Fix spikemonitor for subgroups

---

brian2cuda/templates/common_group.cu
brian2cuda/templates/statemonitor.cu
brian2cuda/tests/__init__.py
brian2cuda/tests/test_neurongroup.py
brian2cuda/tools/test_suite/run_test_suite.py

Fix bug where reading `StateMonitor` indices failed because threads had not returned yet and performed illegal memory accesses.
EDIT: Looks like I also added two commits here that ignore a Brian2 test in the test suite (which fails because of a Brian2CUDA warning which is caught in the test). I added a Brian2CUDA compatible test to the test suite.

Fix `StateMonitr` illegal access

---

brian2cuda/device.py
brian2cuda/templates/group_variable_set.cu
brian2cuda/templates/group_variable_set_conditional.cu
brian2cuda/templates/synapses_push_spikes.cu
brian2cuda/tests/test_neurongroup.py

When setting variables via `group_variables_set` or `group_variable_set_conditional` templates, these are only modified on the device. But sometimes we also need them on the host, which is the case when codeobjects running on the host require them (e.g. synapses connect calls with condition or synapse variables in before run synapses push spikes).
This PR makes sure all variables modified in `group_variable_set(_conditional)` are always copied back to host.

Copy variables modified on device correctly to host

---

brian2cuda/brianlib/spikequeue.h
brian2cuda/device.py
brian2cuda/templates/objects.cu
brian2cuda/templates/synapses.cu
brian2cuda/templates/synapses_push_spikes.cu
brian2cuda/tests/test_network_multiple_runs.py
brian2cuda/tests/test_neurongroup.py
brian2cuda/tests/test_synaptic_propagations.py
brian2cuda/tools/benchmarking/run_benchmark_suite.py

This PR closes #83 and #86.
Follow-up issues are in #301 and #302

Sort multiple run bugs

---

brian2cuda/cuda_prefs.py
brian2cuda/tests/test_cuda_generator.py
brian2cuda/tests/test_gpu_detection.py
brian2cuda/tests/test_network_multiple_runs.py
brian2cuda/tests/test_stringtools.py
brian2cuda/tests/test_synaptic_propagations.py
docs_sphinx/introduction/known_issues.rst

This PR fixes some remaining minor issues that led to some test fails and marks tests failing for known issues as `xfail`, such that the test suite doesn't fail (since these tests fail expectedly).
I just ran the test suite via
```python
import brian2cuda
brian2cuda.test(long_tests=True)
```
And for the first time, I got
```
Running Brian2CUDA version 0.post0.dev1157 from /cognition/home/denis/projects/brian2cuda/brian2cuda_repository/brian2cuda
Resetting to default preferences
Running tests in /cognition/home/denis/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2, /cognition/home/denis/projects/brian2cuda/brian2cuda_repository/brian2cuda/tests  (including long tests)
Running Brian version 2.4.2 from '/cognition/home/denis/projects/brian2cuda/brian2cuda_repository/froze …
```

Get test suite to pass

---

.gitignore
brian2cuda/__init__.py
brian2cuda/cuda_generator.py
brian2cuda/cuda_prefs.py
brian2cuda/device.py
brian2cuda/templates/main.cu
brian2cuda/templates/objects.cu
brian2cuda/tests/features/cuda_configuration.py
brian2cuda/tests/test_cuda_generator.py
brian2cuda/tests/test_gpu_detection.py
brian2cuda/tests/test_neurongroup.py
brian2cuda/tests/test_random_number_generation.py
brian2cuda/utils/gputools.py
frozen_repos/brian2.diff
pyproject.toml

This PR should move Brian2CUDA to compatibility with Brian 2.6, in particular with its useful new `run_args` feature.
Two remarks:
1. The C++ code for the `run_args` feature is an ugly mix of compile-time and run-time code, hopefully we can refactor this nicely in the future (it shouldn't have to be duplicated between Brian2 and Brian2CUDA in the first place).
2. I made it easier to use Brian2's logging feature for external packages like Brian2CUDA, but unfortunately there was a little bug (already fixed, but not in the 2.6.0 release, see brian-team/brian2#1519). Brian tests were meant to ignore log messages from packages not coming from `brian2`, but it erroneously included all package names *starting* with `brian2`, so `brian2cuda` log messages were still counted...

Update for Brian 2.6

---

brian2cuda/tests/test_neurongroup.py
pyproject.toml

Updates the Brian dependency to version 2.7 – nothing affecting Brian2CUDA happened in this release, except that we no longer have to overwrite `test_semantics_floor_division`, since brian-team/brian2#1519 fixed the `catch_logs` context manager.
The main reason for the Brian 2.7 release is its numpy 2.0 compatibility. It would be nice to have a Brian2CUDA release alongside it.

Update for Brian 2.7
